server:
  port: 8080
spring:
  main:
    web-application-type: REACTIVE
    allow-bean-definition-overriding: true
  cloud:
    gateway:
#      default-filters:
#        -DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: resource-server-imbd
          uri: http://localhost:8086
          predicates:
            - Path=/api/**
          filters:
            - TokenRelay=
        - id: web-app
          uri: http://localhost:3000/
          predicates:
            - Path=/**
  security:
    oauth2:
      client:
        provider:
          oauth2server-netflix:
            issuer-uri: http://localhost:8100
        registration:
          proxy-client:
            client-id: client
            client-name: Login Via Netflix
            client-secret: secret
            provider: oauth2server-netflix
            client-authentication-method: client_secret_basic
            redirect-uri: http://localhost:8080/login/oauth2/code/proxy-client
            scope:
              - openid